# Site settings
# baseurl = "http://localhost:1313/"
languageCode = "en-us"
title = "Meexle Sync"
theme = "hugo-agency-theme"


[params]

	name = "Sergei Emelianov"
	description = "Meexle provides Salesforce organization data synchronization and backup. Meexle Sync Tools give you the power of controlling and understanding your data, presenting you the power of building industry-standard analysis on a nosql data arrays"
	email = "meexle@meexle.com"


	# Navigation
	[params.navigation]
		brand = "Meexle"
		synctool = "Products"
		buy = "Buy"
		about = "About"
		example = "Ideas"
		contact = "Contact"


	# Hero section
	[params.hero]
		# To change the background image of the hero, replace 'header-bg.jpg' in
		# the 'static/img' folder.
		title = "Meexle Sync Tool has arrived!"
		subtitle = "Analyze, Understand and Tune your business"
		buttonText = "Purchase Subscription"


	# Synctool section
	[params.synctool]
		title = "Sync Tool"
		subtitle = "Meexle Synchronization Tool for Salesforce keeps real-time projection of your organization data in a NoSQL storage, allowing you to analyze, understand and tune your business metrics to manage effective sales."

		[[params.synctool.list]]
			icon = "fa-gears"
			title = "Data Backup"
			description = "Meexle Sync can be used to schedule backups for your entire Salesforce organization, providing industry-standard security and saving up extra storage provisioning fees. Meexle backs up data in nosql data arrays."

		[[params.synctool.list]]
			icon = "fa-fighter-jet"
			title = "Speed"
			description = "Meexle Sync uses bulk and streaming Salesforce API, traffic compression and other techniques to make initial dataload lightning fast and ongoing updates instantly available in your NoSQL database."

		[[params.synctool.list]]
			icon = "fa-cubes"
			title = "NoSQL flavours"
			description = "Chosing *NoSQL* storage option for your *data* opens up unlimited *analytic* opportuniites. Currently *MongoDB* is supported and Apache HBase support is in development. Support for other NoSQL flavours such as Apache Cassandra is on our plans."

		[[params.synctool.list]]
			icon = "fa-line-chart"
			title = "Analytics"
			description = "With Meexle Sync the power of distributed data processing possible with a NoSQL database charged with your data will be unleashed."

		[[params.synctool.list]]
			icon = "fa-print"
			title = "Reporting"
			description = "Salesforce data made instantly available in a NoSQL database makes it possible to perform data aggregations that weren't available on your Salesforce instance due to not enought computational power and various platform limits."

		[[params.synctool.list]]
			icon = "fa-legal"
			title = "No Limits"
			description = "Meexle Sync intelligently chooses best and proven techniques to communicate with Salesforce and optimizes API calls."

	# Portfolio section
	[params.buy]
		# All projects defined in their own files. You can find example projects
		# at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
		# at the root of this Hugo site.
		# For more informtion take a look at the README.
		title = "Subscription Plans"
		subtitle = "Meexle Services are distributed by subscription only. Test subscription is available upon request"

		[params.plans.modal]
	            client = "Client"
            	date = "Date"
            	category = "Category"
            	buttonText = "Close project"

    # About section
	[params.about]
		title = "Meexle Sync Process"
		subtitle = "Meexle Sync is simple"
		endpoint = "Enjoy<br>your<br>data"

		# The events will be listed from the top to the bottom.
		# All images are stored under 'static/img/about'.
		# Replace them with your own.
		[[params.about.events]]
			img = "1.png"
			title = "Subscribe"
			description = "Meexle Subscription Plans offer flexebility and do adjust to your needs"

		[[params.about.events]]
			img = "2.png"
			title = "Install"
			description = "Install MeexleClient application from AppExchange"

		[[params.about.events]]
			img = "3.png"
			title = "Configure"
			description = "Assemble synchronization configuration and sumbit the file to Meexle"


	# Team section
	[params.example]
		title = "Meexle In Use"
		subtitle = "Meexle produces data arrays that may be used at other cloud services"
		description = "Our ambitions reach far beyond just data synchronization"

		[[params.example.members]]
			img = "amazon-aws.png"
			name = "Amazon Web Service"
			position = "Feed data to Cassandra and process with Amazon Machine Learning"
			
		[[params.example.members]]
			img = "IBM-BlueMix.jpg"
			name = "IBM BlueMix"
			position = "Use data prepared by Meexle with Watson solutions"

	# Client section
	# All the clients' logos are stored under 'static/img/logos'.
	# Replace them with your clients's logos.
	[[params.clients]]
		logo = "salesforce-logo.png"
		link = "http://login.salesforce.com"

	# Contact section
	[params.contact]
		title = "Contact us"
		subtitle  = "We are open to comments and questions."
		buttonText = "Send message"

		# 'warning' defines error messages for invalid inputs
		[params.contact.form.fname]
			text = "Your First Name *"
			warning = "Please enter your fisrt name."
		
		[params.contact.form.lname]
			text = "Your Last Name *"
			warning = "Please enter your last name."

		[params.contact.form.company]
			text = "Company"
			warning = "Please enter your company name."

		[params.contact.form.email]
			text = "Your Email *"
			warning = "Please enter your email address."

		[params.contact.form.phone]
			text = "Your Phone"
			warning = "Please enter your phone number."

		[params.contact.form.message]
			text = "Your Message *"
			warning = "Please enter a message."


	# Footer section
	[params.footer]
		copyright = "Meexle.com"
		
		[[params.footer.social]]
			icon = "fa-twitter"
			link = "https://twitter.com/syemialy"

		[[params.footer.social]]
			icon = "fa-facebook"
			link = "https://www.facebook.com/sergei.emelianov"

		[[params.footer.social]]
			icon = "fa-linkedin"
			link = "https://www.linkedin.com/in/sergeiemelianov"

		[[params.footer.quicklinks]]
			text = "Privacy Policy"
			link = "#"

		[[params.footer.quicklinks]]
			text = "Terms of Use"
			link = "#"
